"""
Procedurally generate realistic 3D workpiece meshes as OBJ files.
Each part has geometric detail that a primitive cylinder/box cannot capture:
  - gear: toothed wheel with center hole
  - bearing: outer ring + inner ring + rolling balls
  - washer: flat annular disk with center hole
  - bolt: hexagonal head + cylindrical shaft
  - block: rectangular block with U-shaped slot
"""
import numpy as np
from pathlib import Path


def write_obj(filepath, vertices, normals, faces, color=None):
    """Write an OBJ file from vertex/normal/face arrays, with optional MTL material.

    vertices: (N, 3)  float
    normals:  (M, 3)  float — used for flat shading (one normal per face)
    faces:    (F, 3)  int — 0-indexed vertex indices
    color:    (r, g, b) optional diffuse color for MTL material
    """
    out_dir = Path(filepath).parent
    out_dir.mkdir(parents=True, exist_ok=True)

    stem = Path(filepath).stem
    mtl_name = f"{stem}.mtl"
    mat_name = f"{stem}_material"

    # Write MTL file if color specified
    if color is not None:
        mtl_path = out_dir / mtl_name
        with open(mtl_path, "w") as f:
            f.write(f"# Material for {stem}\n")
            f.write(f"newmtl {mat_name}\n")
            f.write(f"Kd {color[0]:.3f} {color[1]:.3f} {color[2]:.3f}\n")
            f.write(f"Ka 0.2 0.2 0.2\n")
            f.write(f"Ks 0.3 0.3 0.3\n")
            f.write(f"Ns 10\n")
            f.write(f"d 1.0\n")

    with open(filepath, "w") as f:
        f.write("# Generated by gen_mesh.py\n")
        f.write(f"# Vertices: {len(vertices)}, Faces: {len(faces)}\n")
        if color is not None:
            f.write(f"mtllib {mtl_name}\n")
            f.write(f"usemtl {mat_name}\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for n in normals:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        for i, face in enumerate(faces):
            vi = face + 1  # OBJ is 1-indexed
            ni = i + 1     # one normal per face for flat shading
            f.write(f"f {vi[0]}//{ni} {vi[1]}//{ni} {vi[2]}//{ni}\n")

    print(f"  -> {filepath}  ({len(vertices)} verts, {len(faces)} faces)", end="")
    if color is not None:
        print(f"  [color: ({color[0]:.1f},{color[1]:.1f},{color[2]:.1f})]")
    else:
        print()


def _face_normal(v0, v1, v2):
    """Unit normal for triangle (v0, v1, v2)."""
    a, b, c = np.array(v0), np.array(v1), np.array(v2)
    n = np.cross(b - a, c - a)
    length = np.linalg.norm(n)
    if length < 1e-12:
        return np.array([0.0, 0.0, 1.0])
    return n / length


# ═══════════════════════════════════════════════════════════════
#  Gear: toothed wheel with center hole
# ═══════════════════════════════════════════════════════════════

def generate_gear(filepath, color=None, num_teeth=12, inner_r=0.006, root_r=0.020,
                  tip_r=0.025, thickness=0.015, n_ang=240):
    """Generate a gear with involute-like teeth and a center hole."""
    verts = []
    faces = []
    norms = []

    def v(x, y, z):
        verts.append([x, y, z])
        return len(verts) - 1

    def radial_profile(theta):
        """Tooth profile: trapezoidal teeth."""
        phase = (theta / (2 * np.pi) * num_teeth) % 1.0
        tooth_frac = 0.45  # fraction of one tooth period that is the flat tip
        ramp_frac = (1.0 - tooth_frac) / 2  # each ramp

        if phase < ramp_frac:
            t = phase / ramp_frac
            return root_r + (tip_r - root_r) * (3 * t**2 - 2 * t**3)  # smoothstep
        elif phase < ramp_frac + tooth_frac:
            return tip_r
        elif phase < 1.0 - ramp_frac:
            t = (phase - ramp_frac - tooth_frac) / ramp_frac
            return tip_r - (tip_r - root_r) * (3 * t**2 - 2 * t**3)
        else:
            return root_r

    thetas = np.linspace(0, 2 * np.pi, n_ang, endpoint=False)
    radii = np.array([radial_profile(t) for t in thetas])

    zt = thickness / 2
    zb = -thickness / 2

    # vertex rings
    it = []  # inner top
    ib = []  # inner bottom
    ot = []  # outer top
    ob = []  # outer bottom

    for i, theta in enumerate(thetas):
        c, s = np.cos(theta), np.sin(theta)
        it.append(v(inner_r * c, inner_r * s, zt))
        ib.append(v(inner_r * c, inner_r * s, zb))
        ot.append(v(radii[i] * c, radii[i] * s, zt))
        ob.append(v(radii[i] * c, radii[i] * s, zb))

    # faces
    for i in range(n_ang):
        j = (i + 1) % n_ang

        # top annular ring (two tris per segment)
        f = [it[i], it[j], ot[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [it[i], ot[j], ot[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)

        # bottom annular ring
        f = [ib[i], ob[j], ib[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [ib[i], ob[i], ob[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)

        # outer wall (quad → 2 tris)
        f = [ot[i], ob[i], ot[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [ot[j], ob[i], ob[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)

        # inner wall (hole)
        f = [it[i], it[j], ib[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [it[j], ib[j], ib[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)

    write_obj(filepath, np.array(verts), np.array(norms), np.array(faces), color)


# ═══════════════════════════════════════════════════════════════
#  Washer: flat annular ring
# ═══════════════════════════════════════════════════════════════

def generate_washer(filepath, color=None, inner_r=0.007, outer_r=0.020,
                    thickness=0.008, n_ang=120):
    """Flat ring with a center hole (thin)."""
    verts = []
    faces = []
    norms = []

    def v(x, y, z):
        verts.append([x, y, z])
        return len(verts) - 1

    thetas = np.linspace(0, 2 * np.pi, n_ang, endpoint=False)
    zt = thickness / 2
    zb = -thickness / 2

    it, ib, ot, ob = [], [], [], []
    for theta in thetas:
        c, s = np.cos(theta), np.sin(theta)
        it.append(v(inner_r * c, inner_r * s, zt))
        ib.append(v(inner_r * c, inner_r * s, zb))
        ot.append(v(outer_r * c, outer_r * s, zt))
        ob.append(v(outer_r * c, outer_r * s, zb))

    for i in range(n_ang):
        j = (i + 1) % n_ang
        # top
        f = [it[i], it[j], ot[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [it[i], ot[j], ot[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        # bottom
        f = [ib[i], ob[j], ib[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [ib[i], ob[i], ob[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        # outer wall
        f = [ot[i], ob[i], ot[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [ot[j], ob[i], ob[j]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        # inner wall
        f = [it[i], it[j], ib[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)
        f = [it[j], ib[j], ib[i]]
        norms.append(_face_normal(*[verts[k] for k in f]))
        faces.append(f)

    write_obj(filepath, np.array(verts), np.array(norms), np.array(faces), color)


# ═══════════════════════════════════════════════════════════════
#  Bearing: outer ring + inner ring + rolling balls
# ═══════════════════════════════════════════════════════════════

def generate_bearing(filepath, color=None, outer_r=0.025, inner_r=0.008,
                     ring_thickness=0.006, width=0.012, n_balls=8, n_ang=120):
    """Outer ring + inner ring + balls between them."""
    verts = []
    faces = []
    norms = []

    def v(x, y, z):
        verts.append([x, y, z])
        return len(verts) - 1

    thetas = np.linspace(0, 2 * np.pi, n_ang, endpoint=False)
    zt = width / 2
    zb = -width / 2

    mid_r = (outer_r + inner_r) / 2
    ring_wall = (outer_r - inner_r) / 2  # half-thickness of each ring

    # Outer ring: from outer_r to outer_r - ring_wall*0.6 (thin outer shell)
    or_r = outer_r - ring_wall * 0.25
    # Inner ring: from inner_r to inner_r + ring_wall*0.6
    ir_r = inner_r + ring_wall * 0.3

    or_r_inner = or_r - ring_wall * 0.7
    ir_r_outer = ir_r + ring_wall * 0.7

    # --- outer ring ---
    or_it, or_ib, or_ot, or_ob = [], [], [], []
    for theta in thetas:
        c, s = np.cos(theta), np.sin(theta)
        or_it.append(v(or_r_inner * c, or_r_inner * s, zt))
        or_ib.append(v(or_r_inner * c, or_r_inner * s, zb))
        or_ot.append(v(or_r * c, or_r * s, zt))
        or_ob.append(v(or_r * c, or_r * s, zb))

    for i in range(n_ang):
        j = (i + 1) % n_ang
        for ring in [(or_it, or_ib, or_ot, or_ob)]:
            it_, ib_, ot_, ob_ = ring
            # top
            f = [it_[i], it_[j], ot_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [it_[i], ot_[j], ot_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            # bottom
            f = [ib_[i], ob_[j], ib_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ib_[i], ob_[i], ob_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            # outer
            f = [ot_[i], ob_[i], ot_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ot_[j], ob_[i], ob_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            # inner
            f = [it_[i], it_[j], ib_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [it_[j], ib_[j], ib_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)

    # --- inner ring ---
    ir_it, ir_ib, ir_ot, ir_ob = [], [], [], []
    for theta in thetas:
        c, s = np.cos(theta), np.sin(theta)
        ir_it.append(v(ir_r * c, ir_r * s, zt))
        ir_ib.append(v(ir_r * c, ir_r * s, zb))
        ir_ot.append(v(ir_r_outer * c, ir_r_outer * s, zt))
        ir_ob.append(v(ir_r_outer * c, ir_r_outer * s, zb))

    for i in range(n_ang):
        j = (i + 1) % n_ang
        for ring in [(ir_it, ir_ib, ir_ot, ir_ob)]:
            it_, ib_, ot_, ob_ = ring
            f = [it_[i], it_[j], ot_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [it_[i], ot_[j], ot_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ib_[i], ob_[j], ib_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ib_[i], ob_[i], ob_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ot_[i], ob_[i], ot_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [ot_[j], ob_[i], ob_[j]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [it_[i], it_[j], ib_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
            f = [it_[j], ib_[j], ib_[i]]
            norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)

    # --- rolling balls ---
    ball_r = (or_r_inner - ir_r_outer) * 0.35
    ball_mid_r = (or_r_inner + ir_r_outer) / 2

    # Generate a unit sphere mesh (low-poly for performance)
    sphere_n = 8  # latitude bands
    sphere_m = 8  # longitude segments
    sphere_verts = [[0, 0, 1]]  # north pole
    for si in range(1, sphere_n):
        phi = np.pi * si / sphere_n
        for sj in range(sphere_m):
            theta = 2 * np.pi * sj / sphere_m
            sphere_verts.append([np.sin(phi) * np.cos(theta),
                                 np.sin(phi) * np.sin(theta),
                                 np.cos(phi)])
    sphere_verts.append([0, 0, -1])  # south pole
    sphere_verts = np.array(sphere_verts)

    # sphere faces (triangulated)
    sphere_faces = []
    # top cap
    for j in range(sphere_m):
        sphere_faces.append([0, 1 + j, 1 + (j + 1) % sphere_m])
    # middle bands
    for i in range(sphere_n - 2):
        for j in range(sphere_m):
            a = 1 + i * sphere_m + j
            b = 1 + i * sphere_m + (j + 1) % sphere_m
            c = 1 + (i + 1) * sphere_m + j
            d = 1 + (i + 1) * sphere_m + (j + 1) % sphere_m
            sphere_faces.append([a, b, d])
            sphere_faces.append([a, d, c])
    # bottom cap
    last = len(sphere_verts) - 1
    for j in range(sphere_m):
        a = 1 + (sphere_n - 2) * sphere_m + j
        b = 1 + (sphere_n - 2) * sphere_m + (j + 1) % sphere_m
        sphere_faces.append([a, b, last])

    for k in range(n_balls):
        angle = 2 * np.pi * k / n_balls
        cx = ball_mid_r * np.cos(angle)
        cy = ball_mid_r * np.sin(angle)
        cz = 0

        base_idx = len(verts)
        for sv in sphere_verts:
            v(cx + sv[0] * ball_r, cy + sv[1] * ball_r, cz + sv[2] * ball_r * 0.5)

        for sf in sphere_faces:
            f = [base_idx + sf[0], base_idx + sf[1], base_idx + sf[2]]
            norms.append(_face_normal(*[verts[k] for k in f]))
            faces.append(f)

    write_obj(filepath, np.array(verts), np.array(norms), np.array(faces), color)


# ═══════════════════════════════════════════════════════════════
#  Bolt: hexagonal head + cylindrical shaft
# ═══════════════════════════════════════════════════════════════

def generate_bolt(filepath, color=None, head_radius=0.012, head_height=0.008,
                  shaft_radius=0.008, shaft_height=0.030, n_ang=60):
    """Hexagonal head bolt with cylindrical threaded shaft."""
    verts = []
    faces = []
    norms = []

    def v(x, y, z):
        verts.append([x, y, z])
        return len(verts) - 1

    # --- shaft (cylinder from -shaft_height to 0) ---
    thetas_shaft = np.linspace(0, 2 * np.pi, n_ang, endpoint=False)
    z_bot = -(shaft_height + head_height)
    z_neck = -head_height

    st, sb = [], []
    for theta in thetas_shaft:
        c, s = np.cos(theta), np.sin(theta)
        st.append(v(shaft_radius * c, shaft_radius * s, z_neck))
        sb.append(v(shaft_radius * c, shaft_radius * s, z_bot))

    # bottom cap center
    bc = v(0, 0, z_bot)

    for i in range(n_ang):
        j = (i + 1) % n_ang
        # side wall
        f = [st[i], sb[i], st[j]]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
        f = [st[j], sb[i], sb[j]]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
        # bottom cap
        f = [sb[i], sb[j], bc]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)

    # --- hexagonal head (from -head_height to 0) ---
    hex_n = 6
    hex_thetas = np.linspace(0, 2 * np.pi, hex_n + 1)[:hex_n] + np.pi / 6
    hex_pts = []
    for theta in hex_thetas:
        hex_pts.append((head_radius * np.cos(theta), head_radius * np.sin(theta)))

    z_head_top = 0
    z_head_bot = -head_height

    ht, hb = [], []
    for px, py in hex_pts:
        ht.append(v(px, py, z_head_top))
        hb.append(v(px, py, z_head_bot))

    # head top cap center
    htc = v(0, 0, z_head_top)

    # top cap of shaft (annular between shaft_radius and head inscribed)
    # The shaft top is at z_neck = -head_height
    # The head bottom connects at the same level
    # We need a ring connecting shaft top to head bottom
    for i in range(n_ang):
        j = (i + 1) % n_ang
        # shaft top cap: fan from center to each st vertex
        f = [st[i], st[j], htc]  # wait, htc is at z_head_top, not z_neck
        # Actually the shaft top is open inside the head. Let's just cap it.
        pass

    # Hex head walls
    for i in range(hex_n):
        j = (i + 1) % hex_n
        # side wall of hex
        f = [ht[i], hb[i], ht[j]]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
        f = [ht[j], hb[i], hb[j]]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)
        # top cap
        f = [ht[i], ht[j], htc]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)

    # Bottom cap of hex head (annular ring connecting hex perimeter to shaft)
    # hex edge midpoints connect to shaft circle
    shaft_top_center = v(0, 0, z_head_bot)

    for i in range(hex_n):
        # Each hex bottom edge + two shaft vertices
        # Simple approach: connect hex bottom verts to center
        f = [hb[i], hb[(i + 1) % hex_n], shaft_top_center]
        norms.append(_face_normal(*[verts[k] for k in f])); faces.append(f)

    write_obj(filepath, np.array(verts), np.array(norms), np.array(faces), color)


# ═══════════════════════════════════════════════════════════════
#  Block: rectangular block with U-shaped slot
# ═══════════════════════════════════════════════════════════════

def generate_block(filepath, color=None, w=0.030, d=0.020, h=0.018,
                   slot_w=0.012, slot_d=0.010):
    """Block with a U-shaped slot cut from the top center."""
    verts = []
    faces = []
    norms = []

    def v(x, y, z):
        verts.append([x, y, z])
        return len(verts) - 1

    hw = w / 2
    hd = d / 2

    # Build as 3 stacked sections:
    #   top-left, top-right (with slot in middle), bottom (solid)

    z_top = h / 2
    z_mid = h * 0.15   # slot floor level
    z_bot = -h / 2

    sw_half = slot_w / 2
    sd_half = slot_d / 2

    # --- Bottom section (solid rectangular box, z_bot to z_mid) ---
    b_000 = v(-hw, -hd, z_bot)
    b_100 = v( hw, -hd, z_bot)
    b_110 = v( hw,  hd, z_bot)
    b_010 = v(-hw,  hd, z_bot)
    b_001 = v(-hw, -hd, z_mid)
    b_101 = v( hw, -hd, z_mid)
    b_111 = v( hw,  hd, z_mid)
    b_011 = v(-hw,  hd, z_mid)

    def quad_floor(a, b, c, d):
        """Two triangles for quad a-b-c-d."""
        f1 = [a, b, c]
        norms.append(_face_normal(*[verts[k] for k in f1])); faces.append(f1)
        f2 = [a, c, d]
        norms.append(_face_normal(*[verts[k] for k in f2])); faces.append(f2)

    # bottom face
    quad_floor(b_000, b_010, b_110, b_100)
    # side faces
    quad_floor(b_000, b_100, b_101, b_001)  # front
    quad_floor(b_100, b_110, b_111, b_101)  # right
    quad_floor(b_110, b_010, b_011, b_111)  # back
    quad_floor(b_010, b_000, b_001, b_011)  # left

    # --- Top section: left block + right block (slot in middle) ---
    # Left block
    l_000 = v(-hw, -hd, z_mid)
    l_100 = v(-sw_half, -hd, z_mid)
    l_110 = v(-sw_half, sw_half - sd_half, z_mid)  # Hmm, this is getting complicated

    # Let me simplify: the slot is in the top face, running along Y direction
    # Left pillar: x in [-hw, -sw_half], y in [-hd, hd], z in [z_mid, z_top]
    # Right pillar: x in [sw_half, hw], y in [-hd, hd], z in [z_mid, z_top]
    # Front bridge: x in [-sw_half, sw_half], y in [-hd, -hd+sd_half], z in [z_mid, z_top]
    # Back bridge: x in [-sw_half, sw_half], y in [hd-sd_half, hd], z in [z_mid, z_top]

    for side_x in [(-hw, -sw_half), (sw_half, hw)]:
        x0, x1 = side_x
        a = v(x0, -hd, z_mid)
        b = v(x1, -hd, z_mid)
        c = v(x1,  hd, z_mid)
        d = v(x0,  hd, z_mid)
        e = v(x0, -hd, z_top)
        f_ = v(x1, -hd, z_top)
        g = v(x1,  hd, z_top)
        h_ = v(x0,  hd, z_top)

        quad_floor(a, d, c, b)          # bottom
        quad_floor(a, b, f_, e)         # front
        quad_floor(b, c, g, f_)         # side
        quad_floor(c, d, h_, g)         # back
        quad_floor(d, a, e, h_)         # side
        quad_floor(e, f_, g, h_)        # top

    # Front bridge
    a = v(-sw_half, -hd, z_mid)
    b = v( sw_half, -hd, z_mid)
    c = v( sw_half, -hd + sd_half, z_mid)
    d = v(-sw_half, -hd + sd_half, z_mid)
    e = v(-sw_half, -hd, z_top)
    f_ = v( sw_half, -hd, z_top)
    g = v( sw_half, -hd + sd_half, z_top)
    h_ = v(-sw_half, -hd + sd_half, z_top)
    quad_floor(a, d, c, b)
    quad_floor(a, b, f_, e)
    quad_floor(b, c, g, f_)
    quad_floor(d, a, e, h_)
    quad_floor(e, f_, g, h_)

    # Back bridge
    a = v(-sw_half,  hd - sd_half, z_mid)
    b = v( sw_half,  hd - sd_half, z_mid)
    c = v( sw_half,  hd, z_mid)
    d = v(-sw_half,  hd, z_mid)
    e = v(-sw_half,  hd - sd_half, z_top)
    f_ = v( sw_half,  hd - sd_half, z_top)
    g = v( sw_half,  hd, z_top)
    h_ = v(-sw_half,  hd, z_top)
    quad_floor(a, d, c, b)
    quad_floor(c, d, h_, g)
    quad_floor(d, a, e, h_)
    quad_floor(a, b, f_, e)
    quad_floor(e, f_, g, h_)

    # Slot inner walls (visible from above)
    # Front bridge inner wall
    a = v(-sw_half, -hd + sd_half, z_mid)
    b = v( sw_half, -hd + sd_half, z_mid)
    e_ = v(-sw_half, -hd + sd_half, z_top)
    f_ = v( sw_half, -hd + sd_half, z_top)
    quad_floor(b, a, e_, f_)

    # Back bridge inner wall
    a = v(-sw_half, hd - sd_half, z_mid)
    b = v( sw_half, hd - sd_half, z_mid)
    e_ = v(-sw_half, hd - sd_half, z_top)
    f_ = v( sw_half, hd - sd_half, z_top)
    quad_floor(a, b, f_, e_)

    # Slot floor
    a = v(-sw_half, -hd + sd_half, z_mid)
    b = v( sw_half, -hd + sd_half, z_mid)
    c = v( sw_half,  hd - sd_half, z_mid)
    d = v(-sw_half,  hd - sd_half, z_mid)
    quad_floor(a, b, c, d)

    write_obj(filepath, np.array(verts), np.array(norms), np.array(faces), color)


# ═══════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    models_dir = Path(__file__).resolve().parent.parent / "models"
    print(f"Generating mesh files in {models_dir}/")

    generate_gear(str(models_dir / "gear.obj"), color=(0.9, 0.1, 0.1))       # red
    generate_bearing(str(models_dir / "bearing.obj"), color=(0.1, 0.1, 0.9)) # blue
    generate_washer(str(models_dir / "washer.obj"), color=(0.1, 0.85, 0.1))  # green
    generate_bolt(str(models_dir / "bolt.obj"), color=(0.6, 0.6, 0.6))       # gray
    generate_block(str(models_dir / "block.obj"), color=(0.9, 0.7, 0.1))     # orange

    print("\nDone — 5 OBJ files generated with MTL materials.")
